<?php

function islandora_collection_manager_menu() {
  $items = array();
  $items['islandora/collection'] = array(
    'title' => t('Collection Management'),
    'page callback' => 'collection_management_wrapper',
    'type' => MENU_CALLBACK,
    'access arguments' => array('manage collections'),
  );

  $items['admin/settings/islandora_collection_manager'] = array(
    'title' => t('Collection Manager Admin'),
    'description' => 'Configure Islandora Collection Module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_collection_management_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['islandora/collection/management'] = array(
    'title' => t('Collection Management'),
    'page callback' => 'islandora_collection_management',
    'type' => MENU_CALLBACK,
    'access arguments' => array('manage collections'),
  );
  return $items;
}

function islandora_collection_manager_perm() {
  return array(
    'manage collections',
    'create batch process',
    'delete entire collections',
  );
}

function collection_management_wrapper($collection_pid) {
  module_load_include('inc', 'fedora_repository', 'ObjectHelper');
  module_load_include('inc', 'fedora_repository', 'api/fedora_utils');
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $objectHelper = new ObjectHelper();
  $content_models = $objectHelper->get_content_models_list($collection_pid);
  return drupal_render(get_collection_management_content($content_models, $collection_pid));
}

function islandora_collection_manager_islandora_tabs($content_models, $pid) {
  if (!variable_get('islandora_add_collection_tabs', TRUE) || !user_access('manage collections')) {
    return;
  }
  module_load_include('inc', 'islandora_collection_manager', 'CollectionManagement');
  $content_model_pids = array();
  foreach ($content_models as $content_model) {
    $content_model_pids[] = $content_model->pid;
  }
  if (in_array('islandora:collectionCModel', $content_model_pids)) {
    return get_collection_management_content($content_models, $pid);
  }
}

function get_collection_management_content($content_models, $pid) {
  module_load_include('inc', 'islandora_collection_manager', 'CollectionManagement');
  module_load_include('inc', 'fedora_repository', 'CollectionClass');

  $data = CollectionClass::getRelatedItems($pid);
  $xml = simplexml_load_string($data);
  $results = count($xml->results->result);

  $list = array();
  $list[] = l(t('Create Child Collection'), "islandora/collection/management/new collection/$pid");
  $list[] = l(t('Manage Collection Policy'), "islandora/collection/management/collection policy/$pid");
  if ($results > 0) {
    $list[] = l(t('Migrate Members of this Collection'), "islandora/collection/management/migrate/$pid");
  }
  $list[] = l(t('Change Content Models'), "islandora/collection/management/change content model/$pid");
  $list[] = l(t('Add or Modify QUERY'), "islandora/collection/management/query/$pid");
  if (user_access('delete entire collections')  && user_access('purge objects and datastreams')) {
    $list[] = l(t('Delete Members of this collection'), "islandora/collection/management/delete/$pid");
  }
  $extras = module_invoke_all('islandora_collection_mangement', $pid);
  foreach ($extras as $extra) {
    $list[] = $extra;
  }
  $content = theme_item_list($list);
  $form['add_collection_tab'] = array(
    '#type' => 'tabpage',
    '#title' => t('Manage This Collection'),
    '#content' => $content,
    '#selected' => FALSE,
  );
  return $form;
}

function islandora_collection_management_admin_settings(&$form_state) {
  $form = array();
  $form['islandora_add_collection_tabs'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add tab to collection view allowing collection management?'),
    '#description' => t('Checking this box will show a collection management tab to qualified users<br/>
      if left unchecked the management screen will be accessed via callback'),
    '#default_value' => variable_get('islandora_add_collection_tabs', TRUE),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_theme().
 */
function islandora_collection_manager_theme() {
  return array(
    'islandora_collection_management_form_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'CollectionManagerTable.inc',
    ),
    'islandora_collectionPolicy_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'CollectionPolicyManagement.inc',
    ),
  );
}

function islandora_collection_management($function, $pid) {
  module_load_include('inc', 'islandora_collection_manager', 'management/CollectionPolicyManagement');
  module_load_include('inc', 'islandora_collection_manager', 'management/DeleteCollection');
  module_load_include('inc', 'islandora_collection_manager', 'management/MoveCollection');
  module_load_include('inc', 'islandora_collection_manager', 'management/ChangeContentModel');
  module_load_include('inc', 'islandora_collection_manager', 'management/CreateChildCollection');
  module_load_include('inc', 'islandora_collection_manager', 'management/AddCustomQuery');
  $mappings = array(
    'collection policy' => 'collection_policy_management',
    'delete' => 'islandora_collection_deletion_form',
    'migrate' => 'islandora_collection_migrate_form',
    'change content model' => 'islandora_collection_change_contentmodel',
    'new collection' => 'islandora_collection_create_child',
    'query' => 'islandora_collection_add_query'
  );
  return drupal_get_form($mappings[$function], $pid);
}