<?php

function islandora_collection_manager_menu() {
  $items = array();
  $items['islandora/collection'] = array(
    'title' => t('Collection Management'),
    'page callback' => 'collection_management_wrapper',
    'type' => MENU_CALLBACK,
    'access arguments' => array('manage collections'),
  );

  $items['admin/settings/islandora_collection_manager'] = array(
    'title' => t('Collection Manager Admin'),
    'description' => 'Configure Islandora Collection Module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_collection_management_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function islandora_collection_manager_perm() {
  return array(
    'manage collections',
    'create batch process',
    'delete entire collections',
  );
}

function collection_management_wrapper($collection_pid) {
  module_load_include('inc', 'fedora_repository', 'ObjectHelper');
  module_load_include('inc', 'fedora_repository', 'api/fedora_utils');
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $objectHelper = new ObjectHelper();
  $content_models = $objectHelper->get_content_models_list($collection_pid);
  return drupal_render(get_collection_management_content($content_models, $collection_pid));
}

function islandora_collection_manager_islandora_tabs($content_models, $pid) {
  if (!variable_get('islandora_add_collection_tabs', TRUE) || !user_access('manage collections')) {
    return;
  }
  module_load_include('inc', 'islandora_collection_manager', 'CollectionManagement');
  $content_model_pids = array();
  foreach ($content_models as $content_model) {
    $content_model_pids[] = $content_model->pid;
  }
  if (in_array('islandora:collectionCModel', $content_model_pids)) {
    return get_collection_management_content($content_models, $pid);
  }
}

function get_collection_management_content($content_models, $pid) {
  module_load_include('inc', 'islandora_collection_manager', 'CollectionManagement');
  module_load_include('inc', 'islandora_collection_manager', 'MoveCollection');
  module_load_include('inc', 'islandora_collection_manager', 'DeleteCollection');

  $content = drupal_get_form('collection_management_form', $pid, $content_models);
  $content .= drupal_get_form('islandora_collection_migrate_form', $pid);
  if (user_access('delete entire collections')) {
    $content .= drupal_get_form('islandora_collection_deletion_form', $pid);
  }

  $form['add_collection_tab'] = array(
    '#type' => 'tabpage',
    '#title' => t('Manage This Collection'),
    '#content' => $content,
    '#selected' => FALSE,
  );
  return $form;
}

function islandora_collection_management_admin_settings(&$form_state) {
  $form = array();
  $form['islandora_add_collection_tabs'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add tab to collection view allowing collection management?'),
    '#description' => t('Checking this box will show a collection management tab to qualified users<br/>
      if left unchecked the management screen will be accessed via callback'),
    '#default_value' => variable_get('islandora_add_collection_tabs', TRUE),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_theme().
 */
function islandora_collection_manager_theme() {
  return array(
    'islandora_collection_management_form_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'CollectionManagerTable.inc',
    )
  );
}